### ISSUE TITLE
composer command without parameters

### ISSUE THREAD

**Issue by MarcBoeing** [spryker/jarvis#12]
I get the following suggest from jarvis:

> Agent Assist
...
We identified that your can safely replace those module by this Spryker feature with the version 202001.0.
Please follow our feature integration guide during this process.
Modules already installed
spryker/agent: 1.1.2
spryker/agent-gui: 1.0.0
spryker-shop/agent-page: 1.3.4
spryker-shop/agent-widget: 1.2.3
You are using all the modules of this feature! To replace those modules by the Spryker feature, just run this command.
composer

I guess just running composer would´t work here :-)

composer.json snippet:
"spryker-feature/agent-assist": "^201907.0"
No other above mentioned composer modules in our composer.json

**Comment by jeremyfourna** [comment]
Hello @MarcBoeing, thank you for your feedback, I will take care of this issue.

**Comment by MarcBoeing** [comment]
Works, thank you.
